/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-08-03 15:08:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.menu;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class addMenu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

    String id = (String) session.getAttribute("loginId");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>메뉴 추가하기</title>\r\n");
      out.write("<script type=\"text/javascript\" src =\"../jquery/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("#oneline{\r\n");
      out.write("\tborder : 1px solid skyblue;\r\n");
      out.write("\tmargin-left:20px;\r\n");
      out.write("}\r\n");
      out.write("#tb{\r\n");
      out.write("\tborder : 1px solid skyblue;\r\n");
      out.write("\tcollapse : collapse;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("#btntb{\r\n");
      out.write("\tborder:none;\r\n");
      out.write("}\r\n");
      out.write("button{\r\n");
      out.write("\tbackground-color: #07beb8;\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("\tborder :none;\r\n");
      out.write("\tcursor:pointer;\r\n");
      out.write("\tborder-radius:10px 10px 10px 10px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\twidth: 100px;\r\n");
      out.write("\theight:30px;\r\n");
      out.write("\tmargin-right:20px;\r\n");
      out.write("\tmargin-top:7px;\r\n");
      out.write("}\r\n");
      out.write("input[type=button]{\r\n");
      out.write("\tbackground-color: #07beb8;\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("\tborder :none;\r\n");
      out.write("\tcursor:pointer;\r\n");
      out.write("\tborder-radius:10px 10px 10px 10px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\twidth: 100px;\r\n");
      out.write("\theight:30px;\r\n");
      out.write("\tmargin-left:60px;\r\n");
      out.write("\tmargin-top:10px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<h1 style=\"font-align:right;\">메뉴 추가</h1>\r\n");
      out.write("\r\n");
      out.write("<div id=\"oneline\">\r\n");
      out.write("\r\n");
      out.write("<div id=\"menu\">\r\n");
      out.write("<table id=\"tb\" >\r\n");
      out.write("<col width=\"400\">\r\n");
      out.write("<tr style='background-color:lightgrey;' id=\"basicrow\"><th style='font-weight:bold; text-align:center;'>MENU</th></tr>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("let len = 0;\r\n");
      out.write("let count = 0;\r\n");
      out.write("$.ajax({\r\n");
      out.write("\t url:\"../menucontroll\",\r\n");
      out.write("\t type:\"get\",\r\n");
      out.write("\t data:\"work=getMenuList&id=");
      out.print(id);
      out.write("\",\r\n");
      out.write("\t datatype:\"text\",\r\n");
      out.write("\t success:function(obj){\r\n");
      out.write("\t\t // 테이블을 지울 일이 있으면 지우기\r\n");
      out.write("\t\tlet mlist = obj.mlist;\r\n");
      out.write("\t\tlen = obj.len;\r\n");
      out.write("\t\t//len = len + 1;\r\n");
      out.write("\t\t//console.log(mlist);\r\n");
      out.write("\t\t$(\"#tb\").eq(-1).after(mlist);\r\n");
      out.write("\t },\r\n");
      out.write("\t error:function(){\r\n");
      out.write("\t\t alert(\"menu error\");\r\n");
      out.write("\t }\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"menubtn\" align=\"right\">\r\n");
      out.write("<table id=\"btntb\">\r\n");
      out.write("<tr><button type=\"button\" id=\"addmenubtn\">addmenu</button><br></tr>\r\n");
      out.write("<tr><button type=\"button\" id=\"delmenubtn\">delmenu</button><br></tr>\r\n");
      out.write("<tr><button type=\"button\" id=\"upbtn\" style='visibility:hidden;'>↑</button><br> </tr>\r\n");
      out.write("<tr><button type=\"button\" id=\"downbtn\" style='visibility:hidden;'>↓</button><br></tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<input type=\"button\" value=\"적용\" id=\"cfmbtn\">\r\n");
      out.write("<input type=\"button\" value=\"back\" id=\"baacktn\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("let index = -1;\r\n");
      out.write("let trindex = -1;\r\n");
      out.write("let bfindex = -1;\r\n");
      out.write("let indid =\"\";\r\n");
      out.write("function setRowId(rv){\r\n");
      out.write("\tbfindex = trindex;\r\n");
      out.write("\ttrindex = rv.id;\r\n");
      out.write("\t\r\n");
      out.write("\tif(bfindex != -1 && bfindex != trindex){\r\n");
      out.write("\t\tindid = '#'+bfindex;\r\n");
      out.write("\t\t$(indid).attr('style','background-color:skyblue; border:none; text-align:center;');\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tindid = '#'+trindex;\r\n");
      out.write("\t$(indid).attr('style','background-color:yellow');\r\n");
      out.write("\t//$(indid).parents(\"tr\").attr('style','background-color:pink');\r\n");
      out.write("\tindex = $(indid).parents(\"tr\").attr(\"id\");\r\n");
      out.write("\tindex = index.replace(\"tr\",\"\");\r\n");
      out.write("\t//console.log(index);\r\n");
      out.write("\r\n");
      out.write("\t$(\"#upbtn\").prop(\"style\",\"visibility:visible\");\r\n");
      out.write("\t$(\"#downbtn\").prop(\"style\",\"visibility:visible\");\r\n");
      out.write("}\r\n");
      out.write("$(\"#baacktn\").click(function(){\r\n");
      out.write("\tlocation.href=\"../blog.jsp\";\r\n");
      out.write("});\r\n");
      out.write("$(\"#upbtn\").click(function(){\r\n");
      out.write("\tcount = count -1;\r\n");
      out.write("\tlet uprow = $(indid).parent().parent();\r\n");
      out.write("\tuprow.prev().before(uprow);\r\n");
      out.write("});\r\n");
      out.write("$(\"#downbtn\").click(function(){\r\n");
      out.write("\tcount = count +1;\r\n");
      out.write("\tlet drow = $(indid).parent().parent();\r\n");
      out.write("\tdrow.next().after(drow);\r\n");
      out.write("})\r\n");
      out.write("$(\"#addmenubtn\").click(function(){\r\n");
      out.write("\tlet addTo = document.getElementById(\"tb\");\r\n");
      out.write("\r\n");
      out.write("\tlet row = addTo.insertRow(addTo.rows.length);\r\n");
      out.write("\tlet cell = row.insertCell(0);\r\n");
      out.write("\tlet newrow = \"<tr ><input type='text' id='newone' name='newmenu' placeholder='input menu name'></tr>\";\r\n");
      out.write("\tcell.innerHTML = newrow;\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("$(\"#delmenubtn\").click(function(){\r\n");
      out.write("\tlet mname = $(indid).val();\r\n");
      out.write("\tlet str = \"#mseq\"+index;\r\n");
      out.write("\tlet mseq = $(str).val();\r\n");
      out.write("\tconsole.log(mname + \" \"+ mseq);\r\n");
      out.write("\tif(mname != \"게시판\"){\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\t url:\"../menucontroll\",\r\n");
      out.write("\t\t type:\"get\",\r\n");
      out.write("\t\t data:\"work=delone&id=");
      out.print(id);
      out.write("&seq=\"+mseq,\r\n");
      out.write("\t\t datatype:\"text\",\r\n");
      out.write("\t\t success:function(obj){\r\n");
      out.write("\t\t\tif(obj.conf==\"ok\"){\r\n");
      out.write("\t\t\t\twindow.location.reload();\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\talert(\"정상적으로 삭제 되지 않았습니다\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t },\r\n");
      out.write("\t\t error:function(){\r\n");
      out.write("\t\t\t alert(\"error\");\r\n");
      out.write("\t\t }\r\n");
      out.write("\t});\t\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("$(\"#cfmbtn\").click(function(){\r\n");
      out.write("\t// jquery : when id doesn't exist, return 0\r\n");
      out.write("\tif($(\"#newone\").length > 0 ){ //document.getElementById(\"newone\")\r\n");
      out.write("\t\tlet newstr = $(\"#newone\").val();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\t url:\"../menucontroll\",\r\n");
      out.write("\t\t\t type:\"get\",\r\n");
      out.write("\t\t\t data:\"work=addone&id=");
      out.print(id);
      out.write("&mname=\"+newstr,\r\n");
      out.write("\t\t\t datatype:\"text\",\r\n");
      out.write("\t\t\t success:function(obj){\r\n");
      out.write("\t\t\t\tif(obj.conf==\"ok\"){\r\n");
      out.write("\t\t\t\t\twindow.location.reload();\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\talert(\"정상적으로 추가가 되지 않았습니다\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t },\r\n");
      out.write("\t\t\t error:function(){\r\n");
      out.write("\t\t\t\t alert(\"error\");\r\n");
      out.write("\t\t\t }\r\n");
      out.write("\t\t});\t\r\n");
      out.write("\t}else{ // up down\r\n");
      out.write("\t\tstr = \"#mseq\"+index;\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\t url:\"../menucontroll\",\r\n");
      out.write("\t\t\t type:\"get\",\r\n");
      out.write("\t\t\t data:\"work=moverow&id=");
      out.print(id);
      out.write("&count=\"+count+\"&index=\"+index+\"&seq=\"+$(str).val(),\r\n");
      out.write("\t\t\t datatype:\"text\",\r\n");
      out.write("\t\t\t success:function(obj){\r\n");
      out.write("\t\t\t\tif(obj.conf==\"ok\"){\r\n");
      out.write("\t\t\t\t\thistory.go(0);\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\talert(\"정상적으로 추가가 되지 않았습니다\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t },\r\n");
      out.write("\t\t\t error:function(){\r\n");
      out.write("\t\t\t\t alert(\"error\");\r\n");
      out.write("\t\t\t }\r\n");
      out.write("\t\t});\t\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
