/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-07-30 06:50:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<script type=\"text/javascript\" src =\"./jquery/jquery-3.5.1.min.js\"></script>\n");
      out.write("<link rel=\"stylesheet\" href=\"https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\"> \n");
      out.write("<script src=\"//code.jquery.com/ui/1.11.4/jquery-ui.min.js\"></script>\n");
      out.write("<script src=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\n");
      out.write("<script src=\"https://use.fontawesome.com/releases/v5.2.0/js/all.js\"></script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("function sample4_execDaumPostcode() {\n");
      out.write("    new daum.Postcode({\n");
      out.write("        oncomplete: function(data) {\n");
      out.write("            // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\n");
      out.write("\n");
      out.write("            // 도로명 주소의 노출 규칙에 따라 주소를 표시한다.\n");
      out.write("            // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\n");
      out.write("            var roadAddr = data.roadAddress; // 도로명 주소 변수\n");
      out.write("            var extraRoadAddr = ''; // 참고 항목 변수\n");
      out.write("\n");
      out.write("            // 법정동명이 있을 경우 추가한다. (법정리는 제외)\n");
      out.write("            // 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\n");
      out.write("            if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){\n");
      out.write("                extraRoadAddr += data.bname;\n");
      out.write("            }\n");
      out.write("            // 건물명이 있고, 공동주택일 경우 추가한다.\n");
      out.write("            if(data.buildingName !== '' && data.apartment === 'Y'){\n");
      out.write("               extraRoadAddr += (extraRoadAddr !== '' ? ', ' + data.buildingName : data.buildingName);\n");
      out.write("            }\n");
      out.write("            // 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.\n");
      out.write("            if(extraRoadAddr !== ''){\n");
      out.write("                extraRoadAddr = ' (' + extraRoadAddr + ')';\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            // 우편번호와 주소 정보를 해당 필드에 넣는다.\n");
      out.write("            document.getElementById('sample4_postcode').value = data.zonecode;\n");
      out.write("            document.getElementById(\"sample4_roadAddress\").value = roadAddr;\n");
      out.write("            document.getElementById(\"sample4_jibunAddress\").value = data.jibunAddress;\n");
      out.write("            \n");
      out.write("            // 참고항목 문자열이 있을 경우 해당 필드에 넣는다.\n");
      out.write("/*             if(roadAddr !== ''){\n");
      out.write("                document.getElementById(\"sample4_extraAddress\").value = extraRoadAddr;\n");
      out.write("            } else {\n");
      out.write("                document.getElementById(\"sample4_extraAddress\").value = '';\n");
      out.write("            } */\n");
      out.write("\n");
      out.write("            var guideTextBox = document.getElementById(\"guide\");\n");
      out.write("            // 사용자가 '선택 안함'을 클릭한 경우, 예상 주소라는 표시를 해준다.\n");
      out.write("            if(data.autoRoadAddress) {\n");
      out.write("                var expRoadAddr = data.autoRoadAddress + extraRoadAddr;\n");
      out.write("                guideTextBox.innerHTML = '(예상 도로명 주소 : ' + expRoadAddr + ')';\n");
      out.write("                guideTextBox.style.display = 'block';\n");
      out.write("\n");
      out.write("            } else if(data.autoJibunAddress) {\n");
      out.write("                var expJibunAddr = data.autoJibunAddress;\n");
      out.write("                guideTextBox.innerHTML = '(예상 지번 주소 : ' + expJibunAddr + ')';\n");
      out.write("                guideTextBox.style.display = 'block';\n");
      out.write("            } else {\n");
      out.write("                guideTextBox.innerHTML = '';\n");
      out.write("                guideTextBox.style.display = 'none';\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    }).open();\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("<style type=\"text/css\">\n");
      out.write("body{\n");
      out.write("\tbackground: linear-gradient(to right, skyblue, pink);\n");
      out.write("}\n");
      out.write("#oneline{\n");
      out.write("\tborder : 2px solid white;\n");
      out.write("\twidth : 700px;\n");
      out.write("\theight : 850px;\n");
      out.write("\topacity : 0.7;\n");
      out.write("\tmargin-left : 35%;\n");
      out.write("}\n");
      out.write("#info{\n");
      out.write("\twidth:300px;\n");
      out.write("\theight:30px;\n");
      out.write("\tmargin-top:20px;\n");
      out.write("\tpadding-top : 10px;\n");
      out.write("\tmargin-left: 40px;\n");
      out.write("\tpadding-left: 30px;\n");
      out.write("\tcolor:white;\n");
      out.write("\tfont-size:26pt;\n");
      out.write("\tfont-weight: 1200;\n");
      out.write("\tletter-spacing: -5px;\n");
      out.write("\t/* text-shadow: 2px 2px 5px #0077b6; */\n");
      out.write("\t/* box-shadow : 2px 2px 2px #0077b6; */\n");
      out.write("\tborder-radius: 0.3em;\n");
      out.write("\t/* text-decoration : underline; */\n");
      out.write("}\n");
      out.write("input[type=\"text\"]{\n");
      out.write("\tborder-left : 0px;\n");
      out.write("\tborder-right: 0px;\n");
      out.write("\tborder-top: 0px;\n");
      out.write("\tborder-bottom: 1px solid #03045e;\n");
      out.write("\tmargin-left : 40px;\n");
      out.write("\tmargin-top : 20px;\n");
      out.write("\theight:30px;\n");
      out.write("\twidth : 450px;\n");
      out.write("\tborder-radius :5px 5px 5px 5px;\n");
      out.write("/* \tbackground-color:#90e0ef;*/\n");
      out.write("\topacity : 0.7; \n");
      out.write("}\n");
      out.write("input[type=\"button\"]{\n");
      out.write("\tmargin-left:30px;\n");
      out.write("\theight : 35px;\n");
      out.write("\twidth : 140px;\n");
      out.write("\tbackground-color:#07beb8;\n");
      out.write("\tfont-weight:750;\n");
      out.write("\tcolor: white;\n");
      out.write("\tborder:none;\n");
      out.write("\tcursor:pointer;\n");
      out.write("\tborder-radius:10px 10px 10px 10px;\n");
      out.write("\ttext-align: center;\n");
      out.write("\topacity : 0.7;\n");
      out.write("}\n");
      out.write("input[type=\"checkbox\"]{\n");
      out.write("\tborder:none;\n");
      out.write("\tmargin-left : 40px;\n");
      out.write("\tmargin-top : 20px;\n");
      out.write("}\n");
      out.write(".c{\n");
      out.write("\tcolor:#343a40;\n");
      out.write("\tfont-weight:950;\n");
      out.write("\tbackground-color:white;\n");
      out.write("\tborder-radius:2px 2px 2px 2px;\n");
      out.write("\tfont-family:굴림;\n");
      out.write("\topacity:0.6;\n");
      out.write("}\n");
      out.write("#pwdlab{\n");
      out.write("\tcolor:red;\n");
      out.write("\tmargin-left : 40px;\n");
      out.write("\tfont-family:굴림;\n");
      out.write("\tfont-size:9pt;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<form id=\"frm\" method=\"post\">\n");
      out.write("<input type=\"hidden\" name=\"work\" value=\"join\">\n");
      out.write("<div id=\"oneline\">\n");
      out.write("<p id=\"info\">회원가입</p>\n");
      out.write("\n");
      out.write("<input type=\"text\" name=\"id\" id=\"_id\" placeholder=\"아이디를 입력해주세요(필수 입력)\" required>\n");
      out.write("<input type=\"button\" id=\"idBtn\" value=\"아이디 확인\"><br>\n");
      out.write("\n");
      out.write("<input type=\"text\" name=\"nickname\" id=\"nickname\" placeholder=\"별명을 입력해주세요(필수 입력)\" required>\n");
      out.write("\n");
      out.write("<input type=\"text\" name=\"pwd\" id=\"_pwd\" placeholder=\"비밀번호를 입력해주세요(필수 입력)\" required><br>\n");
      out.write("<input type=\"text\" name=\"pwddb\" id=\"_pwddb\" placeholder=\"비밀번호 확인\" required><br>\n");
      out.write("<p id='pwdlab'></p>\n");
      out.write("\n");
      out.write("<input type=\"text\" id=\"birthday\" name=\"birthday\" placeholder=\"생년월일을 선택해주세요(필수 입력)\" required autocomplete=\"off\"><br>\n");
      out.write("\n");
      out.write("<input type=\"text\" id=\"sample4_postcode\" name=\"postcode\" placeholder=\"우편번호\">\n");
      out.write("<input type=\"button\" onclick=\"sample4_execDaumPostcode()\" value=\"우편번호 찾기\">\n");
      out.write("<input type=\"text\" id=\"sample4_roadAddress\" name=\"roadaddr\" placeholder=\"도로명주소\"><br>\n");
      out.write("<input type=\"text\" id=\"sample4_jibunAddress\" name=\"jibunaddr\" placeholder=\"지번주소\"><br>\n");
      out.write("<span id=\"guide\" style=\"color:#999;display:none\"></span>\n");
      out.write("<input type=\"text\" id=\"sample4_detailAddress\" name=\"detailaddr\" placeholder=\"상세주소\"><br>\n");
      out.write("<!-- <input type=\"text\" id=\"sample4_extraAddress\" placeholder=\"참고항목\"> -->\n");
      out.write("\n");
      out.write("<input type=\"text\" id=\"pnumber\" name=\"pnumber\" placeholder=\"전화번호를 입력해주세요 (-생략)\">\n");
      out.write("<input type=\"button\" id=\"pnumBtn\" value=\"비밀번호 확인\"><br>\n");
      out.write("<input type=\"text\" id=\"email\" name=\"email\" placeholder=\"이메일을 입력해주세요\">\n");
      out.write("<input type=\"button\" id=\"emailBtn\" value=\"이메일 확인\"><br>\n");
      out.write("\n");
      out.write("<input type=\"checkbox\" name=\"snssend\" id=\"msend\" value=\"1\" ><label class=\"c\">메일 수신</label>\n");
      out.write("<input type=\"checkbox\" name=\"snssend\" id=\"ssend\" value=\"2\" ><label class=\"c\">문자 수신</label><br>\n");
      out.write("\n");
      out.write("<input type=\"button\" id=\"joinBtn\" value=\"가입\" style=\"margin-top:50px; margin-left:100px; font-size:18pt;\">\n");
      out.write("</div>\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("let week = ['일','월','화','수','목','금','토']\n");
      out.write("let pwdBool = false;\n");
      out.write("let idchk = false;\n");
      out.write("let pnumchk = false;\n");
      out.write("let emailchk =false;\n");
      out.write("let mbool = false;\n");
      out.write("let sbool = false;\n");
      out.write("let d = new Date();\n");
      out.write("year = d.getFullYear()-20;\n");
      out.write("d = year+\".\"+d.getMonth()+\".\"+d.getDate();\n");
      out.write("console.log(\"d = \"+d);\n");
      out.write("$(document).ready(function() {\n");
      out.write("\t$('#idBtn').click(function() {\n");
      out.write("\t\tlet id = $('#_id').val().replace(\" \",\"\");\n");
      out.write("\t\tif (id== \"\"){\n");
      out.write("\t\t\talert(\"아이디를 입력해주세요\");\n");
      out.write("\t\t\t$(\"#_id\").focus();\n");
      out.write("\t\t}else{\n");
      out.write("\t\t\t$.ajax({\n");
      out.write("\t\t\t\turl:\"./checkcont\",\n");
      out.write("\t\t\t\ttype:\"get\",\n");
      out.write("\t\t\t\tdata:\"work=idchk&id=\"+$(\"#_id\").val(),\n");
      out.write("\t\t\t\tdatatype:\"text\", \n");
      out.write("\t\t\t\tsuccess:function(obj){\n");
      out.write("\t/* \t\t\t\tconsole.log(obj);\n");
      out.write("\t\t\t\t\tconsole.log(obj.b); */\n");
      out.write("\t\t\t\t\tif(!obj.b){\n");
      out.write("\t\t\t\t\t\talert(\"사용 가능한 아이디 입니다\");\n");
      out.write("\t\t\t\t\t\tidchk = true;\n");
      out.write("\t\t\t\t\t}else{\n");
      out.write("\t\t\t\t\t\talert(\"사용 불가능한 아이디 입니다\");\n");
      out.write("\t\t\t\t\t\tidchk=false;\n");
      out.write("\t\t\t\t\t\t$(\"#_id\").val(\"\");\n");
      out.write("\t\t\t\t\t\t$(\"#_id\").focus();\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\terror:function(){\n");
      out.write("\t\t\t\t\talert(\"error\");\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t});\n");
      out.write("\t\t}\n");
      out.write("\t});\n");
      out.write("\t$(\"#pnumBtn\").click(function() {\n");
      out.write("\t\tlet p = $(\"#pnumber\").val().replace(\" \",\"\");\n");
      out.write("\t\tif(p==\"\"){\n");
      out.write("\t\t\talert(\"전화번호를 입력해주세요\");\n");
      out.write("\t\t\t$(\"#pnumber\").focus();\n");
      out.write("\t\t}else{\n");
      out.write("\t\t\t$.ajax({\n");
      out.write("\t\t\t\turl:\"./checkcont\",\n");
      out.write("\t\t\t\ttype:\"get\",\n");
      out.write("\t\t\t\tdata:\"work=pnumchk&pnumber=\"+$(\"#pnumber\").val(),\n");
      out.write("\t\t\t\tdatatype:\"text\", \n");
      out.write("\t\t\t\tsuccess:function(obj){\n");
      out.write("\t/* \t\t\t\tconsole.log(obj);\n");
      out.write("\t\t\t\t\tconsole.log(obj.b); */\n");
      out.write("\t\t\t\t\tif(!obj.b){\n");
      out.write("\t\t\t\t\t\tpnumchk = true;\n");
      out.write("\t\t\t\t\t}else{\n");
      out.write("\t\t\t\t\t\talert(\"이미 존재하는 전화번호 입니다\");\n");
      out.write("\t\t\t\t\t\tpnumchk=false;\n");
      out.write("\t\t\t\t\t\t$(\"#pnumber\").val(\"\");\n");
      out.write("\t\t\t\t\t\t$(\"#pnumber\").focus();\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\terror:function(){\n");
      out.write("\t\t\t\t\talert(\"error\");\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t});\n");
      out.write("\t\t}\n");
      out.write("\t});\n");
      out.write("\t$(\"#emailBtn\").click(function() {\n");
      out.write("\t\tlet p = $(\"#email\").val().replace(\" \",\"\");\n");
      out.write("\t\tif(p==\"\"){\n");
      out.write("\t\t\talert(\"이메일을 입력해주세요\");\n");
      out.write("\t\t\t$(\"#email\").focus();\n");
      out.write("\t\t}else{\n");
      out.write("\t\t\t$.ajax({\n");
      out.write("\t\t\t\turl:\"./checkcont\",\n");
      out.write("\t\t\t\ttype:\"get\",\n");
      out.write("\t\t\t\tdata:\"work=emailchk&email=\"+$(\"#email\").val(),\n");
      out.write("\t\t\t\tdatatype:\"text\", \n");
      out.write("\t\t\t\tsuccess:function(obj){\n");
      out.write("\t/* \t\t\t\tconsole.log(obj);\n");
      out.write("\t\t\t\t\tconsole.log(obj.b); */\n");
      out.write("\t\t\t\t\tif(!obj.b){\n");
      out.write("\t\t\t\t\t\temailchk = true;\n");
      out.write("\t\t\t\t\t}else{\n");
      out.write("\t\t\t\t\t\talert(\"이미 존재하는 전화번호 입니다\");\n");
      out.write("\t\t\t\t\t\temailchk=false;\n");
      out.write("\t\t\t\t\t\t$(\"#email\").val(\"\");\n");
      out.write("\t\t\t\t\t\t$(\"#email\").focus();\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\terror:function(){\n");
      out.write("\t\t\t\t\talert(\"error\");\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t});\n");
      out.write("\t\t}\n");
      out.write("\t});\n");
      out.write("\t$('#birthday').datepicker({\n");
      out.write("\t\tdateFormat : \"yy.mm.dd\",\n");
      out.write("\t\tdateNamesMin: week,\n");
      out.write("\t\tmonthNames: ['1월','2월','3월','4월','5월','6월','7월','8월','9월','10월','11월','12월'],\n");
      out.write("\t\tchangeMonth: true,\n");
      out.write("\t\tchangeYear: true,\n");
      out.write("\t\tyearRange: '-100:-5',\n");
      out.write("\t\tdefaultDate : d\n");
      out.write("\t});\n");
      out.write("\t$('#_pwd').focusout(function() {\n");
      out.write("\t\tlet pwd = $('#_pwd').val().replace(\" \",\"\");\n");
      out.write("\t\tlet num = pwd.search(/[0-9]/g);\n");
      out.write("\t\tlet eng = pwd.search(/[a-z]/g);\n");
      out.write("\t\tlet eng2 = pwd.search(/[A-Z]/g);\n");
      out.write("\t\tlet spe = pwd.search(/[@!%]/gi);\n");
      out.write("\t\tif(pwd == \"\"){\n");
      out.write("\t\t\talert(\"비밀번호를 입력해주시기 바랍니다\");\n");
      out.write("\t\t}else if(pwd.length<8 || pwd.length>16) {\n");
      out.write("\t\t\talert(\"8~16자리로 입력해주시기 바랍니다\");\n");
      out.write("\t\t\t$(\"#_pwd\").val(\"\"); $(\"#_pwd\").focus();\n");
      out.write("\t\t}else if(num<0|| eng<0 || spe <0 || eng2 <0){\n");
      out.write("\t\t\talert(\"영문,숫자,특수무자를 혼합하여 입력해주시기 바랍니다\");\n");
      out.write("\t\t\t$(\"#_pwd\").val(\"\"); $(\"#_pwd\").focus();\n");
      out.write("\t\t}\n");
      out.write("\t});\n");
      out.write("\t$('#joinBtn').on('click',function(){\n");
      out.write("\t\t\n");
      out.write("\t\tif(pwdBool && sbool && mbool \n");
      out.write("\t\t&& $(\"#birthday\").val().replace(\" \",\"\")!=\"\" && $(\"#nickname\").val().replace(\" \",\"\")!=\"\"\n");
      out.write("\t\t\t&& pnumchk && emailchk){\n");
      out.write("\t\t\t$('#frm').attr(\"action\",\"./logjoin\").submit();\n");
      out.write("\t\t}else if(!pwdBool){\n");
      out.write("\t\t\talert(\"비밀번호를 확인해주세요\");\n");
      out.write("\t\t}else if(!sbool){\n");
      out.write("\t\t\talert(\"전화번호를 확인해주세요\");\n");
      out.write("\t\t}else if(!mbool){\n");
      out.write("\t\t\talert(\"메일을 확인 해주세요\");\n");
      out.write("\t\t}else if($(\"#birthday\").val().replace(\" \",\"\")==\"\"){\n");
      out.write("\t\t\talert(\"생일번호를 입력해주세요\");\n");
      out.write("\t\t}else if($(\"#nickname\").val().replace(\" \",\"\")==\"\"){\n");
      out.write("\t\t\talert(\"별명을 확인해주세요\");\n");
      out.write("\t\t}else if(!pnumchk){\n");
      out.write("\t\t\talert(\"전화 번호를 확인해주세요\");\n");
      out.write("\t\t}else if(!emailchk){\n");
      out.write("\t\t\talert(\"이메일을 확인해주세요\");\n");
      out.write("\t\t}\n");
      out.write("\t});\n");
      out.write("\t$('#_pwddb').focusout(function() {\n");
      out.write("\t\tlet pwd1 = $('#_pwd').val();\n");
      out.write("\t\tlet pwd2 = $('#_pwddb').val();\n");
      out.write("\t\tif(pwd1!=pwd2){\n");
      out.write("\t\t\t$('#pwdlab').text('비밀번호가 동일하지 않습니다');\n");
      out.write("\t\t\tpwdBool = false;\n");
      out.write("\t\t}else{\n");
      out.write("\t\t\t$('#pwdlab').text('비밀번호가 동일합니다');\n");
      out.write("\t\t\t$('#pwdlab').attr('color','white');\n");
      out.write("\t\t\tpwdBool = true;\n");
      out.write("\t\t}\n");
      out.write("\t});\n");
      out.write("\t$(\"#msend\").change(function() {\n");
      out.write("\t\tif($(\"#msend\").prop(\"checked\")){\n");
      out.write("\t\t\tif($(\"#email\").val().replace(\" \",\"\")==\"\"){\n");
      out.write("\t\t\t\talert(\"메일을 입력해주세요\");\n");
      out.write("\t\t\t\tmbool = false;\n");
      out.write("\t\t\t\t$(\"#email\").focus();\n");
      out.write("\t\t\t\t$(\"#msend\").prop(\"checked\",false);\n");
      out.write("\t\t\t}else\t\tmbool=true;\n");
      out.write("\t\t}\n");
      out.write("\t});\n");
      out.write("\t$(\"#ssend\").change(function() {\n");
      out.write("\t\tif($(\"#ssend\").prop(\"checked\")){\n");
      out.write("\t\t\tif($(\"#pnumber\").val().replace(\" \",\"\")==\"\"){\n");
      out.write("\t\t\t\talert(\"전화번호를 입력해주세요\");\n");
      out.write("\t\t\t\tsbool = false;\n");
      out.write("\t\t\t\t$(\"#pnumber\").focus();\n");
      out.write("\t\t\t\t$(\"#ssend\").prop(\"checked\",false);\n");
      out.write("\t\t\t}else\t\tsbool=true;\n");
      out.write("\t\t}\n");
      out.write("\t});\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
