/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-08-01 05:22:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<script type=\"text/javascript\" src =\"./jquery/jquery-3.5.1.min.js\"></script>\n");
      out.write("<script src=\"http://lab.alexcican.com/set_cookies/cookie.js\" type=\"text/javascript\" ></script>\n");
      out.write("<style type=\"text/css\">\n");
      out.write("body{\n");
      out.write("\tbackground: linear-gradient(to right, skyblue, pink);\n");
      out.write("}\n");
      out.write("#oneline{\n");
      out.write("\tborder : 2px solid white;\n");
      out.write("\twidth : 600px;\n");
      out.write("\theight : 800px;\n");
      out.write("\topacity : 0.7;\n");
      out.write("\tmargin-left : 35%;\n");
      out.write("}\n");
      out.write("#tdiv{\n");
      out.write("\tcolor: white;\n");
      out.write("\tfont-size : 36px;\n");
      out.write("\tline-height : 1.2em;\n");
      out.write("\tborder : 2px solid white;\n");
      out.write("\tmargin-top: 50px;\n");
      out.write("\tmargin-left : 50px;\n");
      out.write("\twidth : 250px;\n");
      out.write("\theight : 110px;\n");
      out.write("\tpadding-left :10px;\n");
      out.write("\tpadding-top: 10px;\n");
      out.write("}\n");
      out.write("#login{\n");
      out.write("\tbackground-color : white;\n");
      out.write("\twidth: 450px;\n");
      out.write("\theight: 500px;\n");
      out.write("\tmargin-top : 20px;\n");
      out.write("\tmargin-left : 50px;\n");
      out.write("\topacity : 0.4;\n");
      out.write("}\n");
      out.write("input{\n");
      out.write("\theight :20px;\n");
      out.write("\tbakcground-color:white;\n");
      out.write("\tborder-left:none;\n");
      out.write("\tborder-right:none;\n");
      out.write("\tborder-top:none;\n");
      out.write("\tboder: 1px solid white;\n");
      out.write("\tpadding-left:50px;\n");
      out.write("\tmargin-top:60px;\n");
      out.write("}\n");
      out.write("button{\n");
      out.write("\tmargin-left:120px;\n");
      out.write("\tbackground-color: white;\n");
      out.write("\tcolor:lightgrey;\n");
      out.write("\tborder :none;\n");
      out.write("\tborder-radius:10px;\n");
      out.write("\twidth: 100px;\n");
      out.write("\theight:30px;\n");
      out.write("\tmargin-top:20px;\n");
      out.write("}\n");
      out.write("#notrobot{\n");
      out.write("\tvisibility:hidden; \n");
      out.write("}\n");
      out.write("#randomstr{\n");
      out.write("\tbackground-color:black;\n");
      out.write("\twidth: 200px;\n");
      out.write("\theight: 80px;\n");
      out.write("\tmargin-top:120px;\n");
      out.write("\tmargin-left:30px;\n");
      out.write("\tborder: 3px solid white;\n");
      out.write("\tclear:both;\n");
      out.write("\ttext-align: center;\n");
      out.write("\tmargin-bottom:50px;\n");
      out.write("}\n");
      out.write("#testlab{\n");
      out.write("\tfont-size:8px;\n");
      out.write("\tpadding-left:30px;\n");
      out.write("\tmargin-top:-50px;\n");
      out.write("}\n");
      out.write("#randomin{\n");
      out.write("\tcolor:white;\n");
      out.write("\tpadding-left:10px;\n");
      out.write("\tpadding-bottom:-25px;\n");
      out.write("\tfont-size:25px;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<form id=\"frm\" method=\"post\">\n");
      out.write("<input type=\"hidden\" name=\"work\" value=\"login\">\n");
      out.write("<div id=\"oneline\" >\n");
      out.write("<div id=\"tdiv\">\n");
      out.write("너와 나의 <br> &nbsp;&nbsp;&nbsp; 비밀 일기\n");
      out.write("</div>\n");
      out.write("<div id=\"login\">\n");
      out.write("<input type=\"text\" id=\"id\" name=\"id\" placeholder=\"아이디를 입력해주세요\" size=\"30\" value=\"client1\">\n");
      out.write("<input type=\"checkbox\" id=\"chk_save_id\" name=\"chk_save_id\" value=\"chk_save_id\">Save ID<br>\n");
      out.write("<input type=\"password\" id=\"pwd\" name=\"pwd\" placeholder=\"비밀번호를 입력해주세요\" size=\"30\" value=\"abcABC123!@#\" style=\"float:left; \"><br>\n");
      out.write("\n");
      out.write("<div id=\"eyecon\">\n");
      out.write("<img src=\"./images/eye.png\" style=\"height:20px; width:50px; float:left; margin-top:60px; padding-left:20px;\">\n");
      out.write("</div>\n");
      out.write("<div id=\"notrobot\" style=\"visibility:hidden;\">\n");
      out.write("\t<div id=\"randomstr\">\n");
      out.write("\t\t<p id=\"randomin\"></p>\n");
      out.write("\t</div><br>\n");
      out.write("\t<p id=\"testlab\">위의 글자를 따라 써주시기 바랍니다</p>\n");
      out.write("\t<input type=\"text\" id=\"rotest\" name=\"rotest\" size=\"20\" placeholder=\"보안 문자 입력\">\n");
      out.write("\t<p id=\"warnlab\" style=\"padding-left:20px; color:grey; font-size:8pt;\"></p>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<button type=\"button\" id=\"loginbtn\">로그인</button>\n");
      out.write("<button type=\"button\" id=\"joinbtn\">회원가입하기</button>\n");
      out.write("</div>\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("let tbol = false;\n");
      out.write("let count = 0;\n");
      out.write("let str = \"\"; // 랜덤으로 들어갈 값\n");
      out.write("\n");
      out.write("let user_id = $.cookie(\"user_id\"); // cookie를 꺼내온 것\n");
      out.write("if(user_id != null){\t\t\t   // 저장된 쿠키가 존재할 경우\n");
      out.write("\t$(\"#id\").val(user_id);\n");
      out.write("\t$(\"#chk_save_id\").attr(\"checked\",\"checked\");\n");
      out.write("}\n");
      out.write("$(\"#chk_save_id\").click(function(){\n");
      out.write("\tif( $(\"#chk_save_id\").is(\":checked\") ){ // 저장하길 원하는 경우\n");
      out.write("\t\tif($(\"#id\").val().trim()==\"\"){\n");
      out.write("\t\t\talert(\"아이디를 입력해주세요\");\n");
      out.write("\t\t\t$(\"#id\").focus();\n");
      out.write("\t\t\t$(\"#chk_save_id\").prop(\"checked\",false);\n");
      out.write("\t\t}else{\n");
      out.write("\t\t\t// 7일 :: -로 해놓으면 무한대 & path:'/' 모든 경로에 있는 것을 가지고 와라\n");
      out.write("\t\t\t$.cookie(\"user_id\",$(\"#id\").val().trim(),{ expires:7, path:'/'} ); \n");
      out.write("\t\t}\t\n");
      out.write("\t}else{\n");
      out.write("\t\t// 완전 삭제는 없고 기한을 삭제하는 것만 있다\n");
      out.write("\t\t$.removeCookie(\"user_id\",{path:'/'}); \n");
      out.write("\t}\n");
      out.write("});\n");
      out.write("$(document).ready(function() {\n");
      out.write("\t$('#eyecon').mousedown(function() {\n");
      out.write("\t\t$('#pwd').attr('type','text');\n");
      out.write("\t\t$('#eyecon img').attr = $('#eyecon img').attr('src','./images/eyeclose.png');\n");
      out.write("\t});\n");
      out.write("\t$('#eyecon').mouseup(function() {\n");
      out.write("\t\t$('#pwd').attr('type','password');\n");
      out.write("\t\t$('#eyecon img').attr = $('#eyecon img').attr('src','./images/eye.png');\n");
      out.write("\t});\n");
      out.write("\t$('#loginbtn').click(function() {\n");
      out.write("\t\tlet pwd = $('#pwd').val().replace(\" \",\"\");\n");
      out.write("\t\tlet num = pwd.search(/[0-9]/g);\n");
      out.write("\t\tlet eng = pwd.search(/[a-z]/g);\n");
      out.write("\t\tlet eng2 = pwd.search(/[A-Z]/g);\n");
      out.write("\t\tlet spe = pwd.search(/[@!%]/gi);\n");
      out.write("\t\tif($(\"#id\").val().trim() == \"\"){\n");
      out.write("\t\t\talert(\"아이디를 입력해주세요\");\n");
      out.write("\t\t\t$(\"#id\").focus();\n");
      out.write("\t\t}else if($(\"#pwd\").val().trim() == \"\"){\n");
      out.write("\t\t\talert(\"비밀번호를 입력해주세요\");\n");
      out.write("\t\t\t$(\"#pwd\").focus();\n");
      out.write("\t\t}else if(pwd.length<8 || pwd.length>16){\n");
      out.write("\t\t\talert(\"8~16자리로 입력해주시기 바랍니다\");\n");
      out.write("\t\t}else if(num<0|| eng<0 || spe <0 || eng2 <0){\n");
      out.write("\t\t\talert(\"영문,숫자,특수문자를 혼합하여 입력해주시기 바랍니다\");\n");
      out.write("\t\t}else{\n");
      out.write("\t\t\t$.ajax({\n");
      out.write("\t\t\t\t url:\"./checkcont\",\n");
      out.write("\t\t\t\t type:\"post\",\n");
      out.write("\t\t\t\t data:\"work=isLogPos&id=\"+$(\"#id\").val()+\"&pwd=\"+pwd,\n");
      out.write("\t\t\t\t datatype:\"text\",\n");
      out.write("\t\t\t\t success:function(obj){\n");
      out.write("\t\t\t\t\tlet b = obj.b;\n");
      out.write("\t\t\t\t\tconsole.log(count);\n");
      out.write("\t\t\t\t\t if(!b){\n");
      out.write("\t\t\t\t\t\t if(count>3){\n");
      out.write("\t\t\t\t\t\t\t $(\"#notrobot\").attr(\"style\",\"visibility:visible\");\n");
      out.write("\t\t\t\t\t\t\t// console.log($(\"#notrobot\").attr(\"style\"));\n");
      out.write("\t\t\t\t\t\t\t getRandom();\n");
      out.write("\t\t\t\t\t\t\t $(\"#randomin\").text(str);\n");
      out.write("\t\t\t\t\t\t }\n");
      out.write("\t\t\t\t\t\t count++;\n");
      out.write("\t\t\t\t\t\t alert(\"아이디/비밀번호를 다시 확인 해주시기 바랍니다\");\n");
      out.write("\t\t\t\t\t\t $(\"#id\").val(\"\"); $(\"#pwd\").val(\"\"); $(\"#id\").focus();\n");
      out.write("\t\t\t\t\t }else{\n");
      out.write("\t\t\t\t\t\tif(!tbol && count >3){\n");
      out.write("\t\t\t\t\t\t\talert(\"보안 문자를 입력해주세요\");\n");
      out.write("\t\t\t\t\t\t\t$(\"#rotest\").focus();\n");
      out.write("\t\t\t\t\t\t}else{\n");
      out.write("\t\t\t\t\t\t\tcount=0;\n");
      out.write("\t\t\t\t\t\t\tlet id = $(\"#id\").val().replace(\" \",\"\");\n");
      out.write("\t\t\t\t\t\t\t$(\"#frm\").attr(\"action\",\"logjoin?work=login&id=\"+id).submit();\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t }\n");
      out.write("\t\t\t\t },\n");
      out.write("\t\t\t\t error:function(){\n");
      out.write("\t\t\t\t\t alert(\"error\");\n");
      out.write("\t\t\t\t }\n");
      out.write("\t\t\t });\n");
      out.write("\t\t\t}\n");
      out.write("\t});\n");
      out.write("\t$('#joinbtn').click(function() {\n");
      out.write("\t\tlocation.href=\"logjoin?work=movejoin\";\n");
      out.write("\t});\n");
      out.write("\t$('#rotest').focusout(function(){\n");
      out.write("\t\tlet input = $(\"#rotest\").val();\n");
      out.write("\t\tconsole.log(\"str = \"+str+\" , input = \"+ input);\n");
      out.write("\t\tif(str != input){\n");
      out.write("\t\t\t$(\"#warnlab\").text(\"정확하게 입력해주시기 바랍니다\");\n");
      out.write("\t\t\ttbol = false;\n");
      out.write("\t\t}else {\n");
      out.write("\t\t\t$(\"#warnlab\").text(\"정확하게 입력 하였습니다\");\n");
      out.write("\t\t\ttbol=true;\n");
      out.write("\t\t}\n");
      out.write("\t});\n");
      out.write("\tfunction getRandom() {\n");
      out.write("\t\tstr=\"\";\n");
      out.write("\t\tlet num = new Array(5);\n");
      out.write("\t\tfor(i=0; i<num.length; i++){\n");
      out.write("\t\t\tlet n = parseInt((Math.random()*24));\n");
      out.write("\t\t\tif(i%2==0){\n");
      out.write("\t\t\t\tnum[i] = n+\"\";\n");
      out.write("\t\t\t}else{\n");
      out.write("\t\t\t\tnum[i] = String.fromCharCode( ((n+65)+\"\") );\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\tstr += num[i];\n");
      out.write("\t\t}\n");
      out.write("\t\tconsole.log(\"str = \"+str);\n");
      out.write("\t}\n");
      out.write("});\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
